# Generated by Django 4.1.4 on 2023-02-07 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Discipline', '0001_initial'),
        ('Lessons', '0005_alter_lessons_options'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, verbose_name='Group number')),
                ('hm_file', models.FileField(blank=True, null=True, upload_to='HomeWork/', verbose_name='file')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('hm_discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Discipline.discipline', verbose_name='Discipline')),
                ('hm_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lessons.lessons', verbose_name='Lesson')),
                ('hm_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teachers.teachers', verbose_name='Teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'HomeWork',
                'verbose_name_plural': 'HomeWorks',
                'ordering': ['-id'],
            },
        ),
    ]
