# Generated by Django 4.1.4 on 2023-02-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='hm_file',
            new_name='file',
        ),
    ]
