# Generated by Django 4.1.4 on 2023-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-id'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='discipline',
            new_name='discipline_id',
        ),
    ]
