# Generated by Django 4.1.4 on 2023-02-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discipline', '0001_initial'),
        ('Lessons', '0003_rename_discipline_id_lessons_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-id'], 'verbose_name': 'Lessons', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='lessons',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Discipline.discipline'),
        ),
    ]
