# Generated by Django 4.1.4 on 2023-02-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0004_alter_lessons_options_alter_lessons_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-id']},
        ),
    ]
