# Generated by Django 4.1.4 on 2023-02-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0005_alter_lessons_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-id'], 'verbose_name': 'Lessons', 'verbose_name_plural': 'Lessons'},
        ),
    ]
